swagger: "2.0"
info:
  title: match API
  description: Match Application API, You can read and test  the APIs from this documentation
  version: "1.0"
host: localhost:80
consumes:
- application/json
- application/xml
produces:
- application/json
- application/xml
- application/gob
paths:
  /product/v1:
    get:
      tags:
      - products
      summary: list products
      description: |-
        list products

        **Required security scopes for jwt**:
          * `list-products`
      operationId: products#list
      parameters:
      - name: sort_direction
        in: query
        required: false
        type: string
        default: desc
        enum:
        - asc
        - desc
      - name: sort_key
        in: query
        required: false
        type: string
        default: CreatedAt
        enum:
        - CreatedAt
        - ProductID
        - ProductName
      - name: page_number
        in: query
        required: false
        type: integer
        default: 1
      - name: page_size
        in: query
        required: false
        type: integer
        default: 20
      - name: Authorization
        in: header
        description: JWT used for authentication
        required: true
        type: string
      responses:
        "200":
          description: OK response.
          schema:
            $ref: '#/definitions/ProductsListResponseBody'
            required:
            - products
            - pagination
        "401":
          description: Unauthorized response.
          schema:
            $ref: '#/definitions/ProductsListUnauthorizedResponseBody'
      schemes:
      - http
      security:
      - jwt_header_Authorization: []
    post:
      tags:
      - products
      summary: create products
      description: |-
        Create new product

        **Required security scopes for jwt**:
          * `create-product`
      operationId: products#create
      parameters:
      - name: Authorization
        in: header
        description: JWT used for authentication
        required: true
        type: string
      - name: CreateRequestBody
        in: body
        required: true
        schema:
          $ref: '#/definitions/ProductsCreateRequestBody'
          required:
          - product
      responses:
        "200":
          description: OK response.
        "406":
          description: Not Acceptable response.
          schema:
            $ref: '#/definitions/ProductsCreateDublicateDataResponseBody'
      schemes:
      - http
      security:
      - jwt_header_Authorization: []
  /product/v1/{id}:
    put:
      tags:
      - products
      summary: update products
      description: |-
        update existing product

        **Required security scopes for jwt**:
          * `update-product`
      operationId: products#update
      parameters:
      - name: id
        in: path
        description: the product id to be updated
        required: true
        type: integer
        format: int64
      - name: Authorization
        in: header
        description: JWT used for authentication
        required: true
        type: string
      - name: UpdateRequestBody
        in: body
        required: true
        schema:
          $ref: '#/definitions/ProductsUpdateRequestBody'
          required:
          - product
      responses:
        "200":
          description: OK response.
        "404":
          description: Not Found response.
          schema:
            $ref: '#/definitions/ProductsUpdateNotExistResponseBody'
        "406":
          description: Not Acceptable response.
          schema:
            $ref: '#/definitions/ProductsUpdateDublicateDataResponseBody'
      schemes:
      - http
      security:
      - jwt_header_Authorization: []
    delete:
      tags:
      - products
      summary: delete products
      description: |-
        delete existing product

        **Required security scopes for jwt**:
          * `delete-product`
      operationId: products#delete
      parameters:
      - name: id
        in: path
        description: the product id to be updated
        required: true
        type: integer
        format: int64
      - name: Authorization
        in: header
        description: JWT used for authentication
        required: true
        type: string
      responses:
        "200":
          description: OK response.
        "404":
          description: Not Found response.
          schema:
            $ref: '#/definitions/ProductsDeleteNotExistResponseBody'
      schemes:
      - http
      security:
      - jwt_header_Authorization: []
  /product/v1/swagger/swagger.json:
    get:
      tags:
      - swagger
      summary: Download gen/http/openapi.json
      description: JSON document containing the API swagger definition
      operationId: swagger#/product/v1/swagger/swagger.json
      responses:
        "200":
          description: File downloaded
          schema:
            type: file
      schemes:
      - http
definitions:
  ListproductRespResponseBody:
    title: ListproductRespResponseBody
    type: object
    properties:
      productAmount:
        type: integer
        description: product name
        example: 2270221943427951993
        format: int64
      productCost:
        type: integer
        description: product role
        example: 2030721407935608170
        format: int64
      productID:
        type: string
        description: product Id
        example: Doloremque et mollitia omnis.
      productName:
        type: string
        description: product name
        example: Vitae dolores explicabo.
      sellerID:
        type: integer
        description: product role
        example: 5304645770518799555
        format: int64
    example:
      productAmount: 3289388293409851644
      productCost: 5253232518808673988
      productID: Sed in aperiam voluptates ut provident.
      productName: Eos sit.
      sellerID: 465245518370038248
    required:
    - productID
    - productName
    - productAmount
    - productCost
    - sellerID
  PaginationResponseBody:
    title: 'Mediatype identifier: pagination; view=default'
    type: object
    properties:
      current_page:
        type: integer
        description: The current page
        example: 1
        format: int64
      page_size:
        type: integer
        description: 'Max number of records per page '
        example: 3
        format: int64
      total_count:
        type: integer
        description: Total records count
        example: 33
        format: int64
      total_pages:
        type: integer
        description: Total pages
        example: 11
        format: int64
    description: PaginationResponseBody result type (default view)
    example:
      current_page: 1
      page_size: 3
      total_count: 33
      total_pages: 11
  ProductsCreateDublicateDataResponseBody:
    title: 'Mediatype identifier: application/vnd.goa.error; view=default'
    type: object
    properties:
      fault:
        type: boolean
        description: Is the error a server-side fault?
        example: false
      id:
        type: string
        description: ID is a unique identifier for this particular occurrence of the
          problem.
        example: 123abc
      message:
        type: string
        description: Message is a human-readable explanation specific to this occurrence
          of the problem.
        example: parameter 'p' must be an integer
      name:
        type: string
        description: Name is the name of this class of errors.
        example: bad_request
      temporary:
        type: boolean
        description: Is the error temporary?
        example: false
      timeout:
        type: boolean
        description: Is the error a timeout?
        example: true
    description: the error returned the product data is already existing in the database
      (default view)
    example:
      fault: false
      id: 123abc
      message: parameter 'p' must be an integer
      name: bad_request
      temporary: true
      timeout: false
    required:
    - name
    - id
    - message
    - temporary
    - timeout
    - fault
  ProductsCreateInvalidDataResponseBody:
    title: 'Mediatype identifier: application/vnd.goa.error; view=default'
    type: object
    properties:
      fault:
        type: boolean
        description: Is the error a server-side fault?
        example: true
      id:
        type: string
        description: ID is a unique identifier for this particular occurrence of the
          problem.
        example: 123abc
      message:
        type: string
        description: Message is a human-readable explanation specific to this occurrence
          of the problem.
        example: parameter 'p' must be an integer
      name:
        type: string
        description: Name is the name of this class of errors.
        example: bad_request
      temporary:
        type: boolean
        description: Is the error temporary?
        example: false
      timeout:
        type: boolean
        description: Is the error a timeout?
        example: true
    description: the error returned the product data is invalid (default view)
    example:
      fault: true
      id: 123abc
      message: parameter 'p' must be an integer
      name: bad_request
      temporary: false
      timeout: true
    required:
    - name
    - id
    - message
    - temporary
    - timeout
    - fault
  ProductsCreateRequestBody:
    title: ProductsCreateRequestBody
    type: object
    properties:
      product:
        $ref: '#/definitions/productPayloadRequestBody'
    example:
      product:
        productAmount: 1988590285111918327
        productCost: 8869641590945913594
        productName: Officia nulla mollitia.
    required:
    - product
  ProductsDeleteNotExistResponseBody:
    title: 'Mediatype identifier: application/vnd.goa.error; view=default'
    type: object
    properties:
      fault:
        type: boolean
        description: Is the error a server-side fault?
        example: false
      id:
        type: string
        description: ID is a unique identifier for this particular occurrence of the
          problem.
        example: 123abc
      message:
        type: string
        description: Message is a human-readable explanation specific to this occurrence
          of the problem.
        example: parameter 'p' must be an integer
      name:
        type: string
        description: Name is the name of this class of errors.
        example: bad_request
      temporary:
        type: boolean
        description: Is the error temporary?
        example: false
      timeout:
        type: boolean
        description: Is the error a timeout?
        example: true
    description: the error returned when the product is not exists (default view)
    example:
      fault: true
      id: 123abc
      message: parameter 'p' must be an integer
      name: bad_request
      temporary: true
      timeout: true
    required:
    - name
    - id
    - message
    - temporary
    - timeout
    - fault
  ProductsListResponseBody:
    title: ProductsListResponseBody
    type: object
    properties:
      pagination:
        $ref: '#/definitions/PaginationResponseBody'
      products:
        type: array
        items:
          $ref: '#/definitions/ListproductRespResponseBody'
        description: events
        example:
        - productAmount: 8013853793828655752
          productCost: 6014434493214870064
          productID: Ipsa autem qui minima dolor nisi.
          productName: Totam velit.
          sellerID: 6503267676370616177
        - productAmount: 8013853793828655752
          productCost: 6014434493214870064
          productID: Ipsa autem qui minima dolor nisi.
          productName: Totam velit.
          sellerID: 6503267676370616177
        - productAmount: 8013853793828655752
          productCost: 6014434493214870064
          productID: Ipsa autem qui minima dolor nisi.
          productName: Totam velit.
          sellerID: 6503267676370616177
    example:
      pagination:
        current_page: 1
        page_size: 3
        total_count: 33
        total_pages: 11
      products:
      - productAmount: 8013853793828655752
        productCost: 6014434493214870064
        productID: Ipsa autem qui minima dolor nisi.
        productName: Totam velit.
        sellerID: 6503267676370616177
      - productAmount: 8013853793828655752
        productCost: 6014434493214870064
        productID: Ipsa autem qui minima dolor nisi.
        productName: Totam velit.
        sellerID: 6503267676370616177
    required:
    - products
    - pagination
  ProductsListUnauthorizedResponseBody:
    title: 'Mediatype identifier: application/vnd.goa.error; view=default'
    type: object
    properties:
      fault:
        type: boolean
        description: Is the error a server-side fault?
        example: true
      id:
        type: string
        description: ID is a unique identifier for this particular occurrence of the
          problem.
        example: 123abc
      message:
        type: string
        description: Message is a human-readable explanation specific to this occurrence
          of the problem.
        example: parameter 'p' must be an integer
      name:
        type: string
        description: Name is the name of this class of errors.
        example: bad_request
      temporary:
        type: boolean
        description: Is the error temporary?
        example: true
      timeout:
        type: boolean
        description: Is the error a timeout?
        example: true
    description: the error returned when token is invalid (default view)
    example:
      fault: true
      id: 123abc
      message: parameter 'p' must be an integer
      name: bad_request
      temporary: false
      timeout: false
    required:
    - name
    - id
    - message
    - temporary
    - timeout
    - fault
  ProductsUpdateDublicateDataResponseBody:
    title: 'Mediatype identifier: application/vnd.goa.error; view=default'
    type: object
    properties:
      fault:
        type: boolean
        description: Is the error a server-side fault?
        example: true
      id:
        type: string
        description: ID is a unique identifier for this particular occurrence of the
          problem.
        example: 123abc
      message:
        type: string
        description: Message is a human-readable explanation specific to this occurrence
          of the problem.
        example: parameter 'p' must be an integer
      name:
        type: string
        description: Name is the name of this class of errors.
        example: bad_request
      temporary:
        type: boolean
        description: Is the error temporary?
        example: true
      timeout:
        type: boolean
        description: Is the error a timeout?
        example: true
    description: the error returned the product data is already existing in the database
      (default view)
    example:
      fault: true
      id: 123abc
      message: parameter 'p' must be an integer
      name: bad_request
      temporary: false
      timeout: true
    required:
    - name
    - id
    - message
    - temporary
    - timeout
    - fault
  ProductsUpdateInvalidDataResponseBody:
    title: 'Mediatype identifier: application/vnd.goa.error; view=default'
    type: object
    properties:
      fault:
        type: boolean
        description: Is the error a server-side fault?
        example: true
      id:
        type: string
        description: ID is a unique identifier for this particular occurrence of the
          problem.
        example: 123abc
      message:
        type: string
        description: Message is a human-readable explanation specific to this occurrence
          of the problem.
        example: parameter 'p' must be an integer
      name:
        type: string
        description: Name is the name of this class of errors.
        example: bad_request
      temporary:
        type: boolean
        description: Is the error temporary?
        example: false
      timeout:
        type: boolean
        description: Is the error a timeout?
        example: false
    description: the error returned the product data is invalid (default view)
    example:
      fault: false
      id: 123abc
      message: parameter 'p' must be an integer
      name: bad_request
      temporary: false
      timeout: false
    required:
    - name
    - id
    - message
    - temporary
    - timeout
    - fault
  ProductsUpdateNotExistResponseBody:
    title: 'Mediatype identifier: application/vnd.goa.error; view=default'
    type: object
    properties:
      fault:
        type: boolean
        description: Is the error a server-side fault?
        example: false
      id:
        type: string
        description: ID is a unique identifier for this particular occurrence of the
          problem.
        example: 123abc
      message:
        type: string
        description: Message is a human-readable explanation specific to this occurrence
          of the problem.
        example: parameter 'p' must be an integer
      name:
        type: string
        description: Name is the name of this class of errors.
        example: bad_request
      temporary:
        type: boolean
        description: Is the error temporary?
        example: false
      timeout:
        type: boolean
        description: Is the error a timeout?
        example: true
    description: the error returned when the product is not exists (default view)
    example:
      fault: false
      id: 123abc
      message: parameter 'p' must be an integer
      name: bad_request
      temporary: true
      timeout: false
    required:
    - name
    - id
    - message
    - temporary
    - timeout
    - fault
  ProductsUpdateRequestBody:
    title: ProductsUpdateRequestBody
    type: object
    properties:
      product:
        $ref: '#/definitions/productPayloadRequestBody'
    example:
      product:
        productAmount: 1988590285111918327
        productCost: 8869641590945913594
        productName: Officia nulla mollitia.
    required:
    - product
  productPayloadRequestBody:
    title: productPayloadRequestBody
    type: object
    properties:
      productAmount:
        type: integer
        example: 6328167796459552998
        minimum: 0
      productCost:
        type: integer
        example: 220294929924359010
        minimum: 0
      productName:
        type: string
        description: product name
        example: Velit eveniet atque impedit.
    example:
      productAmount: 4910471009746519470
      productCost: 3613475171567110537
      productName: Id ut.
    required:
    - productName
    - productAmount
    - productCost
securityDefinitions:
  jwt_header_Authorization:
    type: apiKey
    description: |-
      Secures endpoint by requiring a valid JWT token retrieved via the signin endpoint.".

      **Security Scopes**:
        * `list-products`: list products
        * `update-product`: update products
        * `delete-product`: delete products
        * `create-product`: create products
    name: Authorization
    in: header
